[workspace]
resolver = "3"
members = ["aoc_tools", "year_2015"]


[workspace.package]
authors = ["Alejandro Fernandez <antarticonorte@gmail.com>"]
license = "MIT"
edition = "2024"
version = "0.1.0"
publish = false

[workspace.dependencies]
aoc_tools = { path = 'aoc_tools' }
